# Generated by Django 5.2.3 on 2025-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='model_used',
            field=models.CharField(default='Multiple', max_length=100),
        ),
    ]
