# Generated by Django 5.2.3 on 2025-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userquery_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='gemini_comparison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='gemini_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='gpt_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='llama_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='mistral_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
